// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsZuYyMfDUQ2IWwTgfbKVYwKdK3aQhxyI',
    appId: '1:364099450563:web:78505149a37723726fd476',
    messagingSenderId: '364099450563',
    projectId: 'signi-84991',
    authDomain: 'signi-84991.firebaseapp.com',
    storageBucket: 'signi-84991.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbHo83dKpaYOyFOhQuixoCv5i3EvcPH2M',
    appId: '1:364099450563:android:f9e4e01b31f37ff06fd476',
    messagingSenderId: '364099450563',
    projectId: 'signi-84991',
    storageBucket: 'signi-84991.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHugc5rgypFWTJw7U8cR5aWQmLWpU_6Rw',
    appId: '1:364099450563:ios:17f19f5a018501ec6fd476',
    messagingSenderId: '364099450563',
    projectId: 'signi-84991',
    storageBucket: 'signi-84991.appspot.com',
    iosBundleId: 'com.example.signio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHugc5rgypFWTJw7U8cR5aWQmLWpU_6Rw',
    appId: '1:364099450563:ios:17f19f5a018501ec6fd476',
    messagingSenderId: '364099450563',
    projectId: 'signi-84991',
    storageBucket: 'signi-84991.appspot.com',
    iosBundleId: 'com.example.signio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsZuYyMfDUQ2IWwTgfbKVYwKdK3aQhxyI',
    appId: '1:364099450563:web:d24c9897297a256c6fd476',
    messagingSenderId: '364099450563',
    projectId: 'signi-84991',
    authDomain: 'signi-84991.firebaseapp.com',
    storageBucket: 'signi-84991.appspot.com',
  );
}
